# Generated by Django 3.2.4 on 2021-07-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='thumbnails',
        ),
    ]
