# Generated by Django 3.2.4 on 2021-07-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210708_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_date',
            new_name='product_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_desc',
            new_name='product_desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_name',
            new_name='product_name',
        ),
    ]
