# Generated by Django 3.2.4 on 2021-07-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('json_item', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='name@name.domain', max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=300)),
                ('phone', models.IntegerField(max_length=13)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='c_desc',
            field=models.CharField(default='No Description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='c_email',
            field=models.CharField(default='name@name.domain', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='c_phone',
            field=models.CharField(default='123', max_length=50),
        ),
    ]
